baseURL = 'https://www.conciergecomputing.com/'
languageCode = 'en-us'
title = 'Concierge Computing test'
theme = 'ananke'
# sectionPagesMenu = 'main'
googleAnalytics = 'G-ZVNEKJ1M38'
[params]
  # site_logo = "images/cc-logo-dall-e.png"
  env = "production"
[menu]
[[menu.main]]
  identifier = "contact"
  name = "Contact Us"
  url = "/contact"
  weight = 10
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about-us/"
  weight = 20
[[menu.main]]
  identifier = "learning"
  name = "Learning"
  url = "/learning/"
  weight = 30
[[menu.main]]
  identifier = "newsletter"
  name = "Newsletter"
  url = "/newsletter/"
  weight = 30


  
# [[params.ananke_socials]]
#     name = "twitter"
# url = "https://twitter.com/GoHugoIO"