baseURL = 'https://www.conciergecomputing.com/'
languageCode = 'en-us'
title = 'Concierge Computing'
theme = 'ananke'

[[params.ananke_socials]]
    name = "twitter"
url = "https://twitter.com/GoHugoIO"